name: Go

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - uses: actions/checkout@v3
    - run: go build -v ./...
    - run: go test -v ./...
    - uses: actions/upload-artifact@v3
      with:
        name: "baiton-${{ matrix.os }}"
        path: |
          baiton
          baiton.exe
